### ISSUE TITLE
建议合入https://github.com/vuejs/awesome-vue

### ISSUE THREAD

**Issue by fishenal** [Plortinus/vue-multiple-pages#1]
不想重复造轮子了，这个很好，感觉多页面需求很多，
建议合入
https://github.com/vuejs/awesome-vue

**Comment by Plortinus** [comment]
这个项目不适合放在awesome-vue里，那里面放组件性质的东西比较好，这个是项目构建类的。项目构建的轮子各式各样，也没有一个统一的标准。

**Comment by Plortinus** [comment]
已合入
