### ISSUE TITLE
可否留个联系。

### ISSUE THREAD

**Issue by LIANGWEIBIAO** [Plortinus/vue-multiple-pages#10]
最近配置webpack有少少问题，可以问一下你吗？

**Comment by Plortinus** [comment]
本项目相关问题可以提issue

**Comment by LIANGWEIBIAO** [comment]
build出来的css和js文件都没带hash。

**Comment by Plortinus** [comment]
`hash`的通过webpack插件[html-webpack-plugin](https://github.com/jantimon/html-webpack-plugin)添加的
