### ISSUE TITLE
template 中的 package.json 少了引用 qs 这个依赖

### ISSUE THREAD

**Issue by tangyingcai** [Plortinus/vue-multiple-pages#12]
很棒的脚手架! 谢谢作者~~
模板中有个小bug~ 提交给你吧~ 
![Uploading image.png…]()

**Comment by Plortinus** [comment]
不需要添加.
`npm i`或者`yarn`安装之后,`qs`依赖是自动安装好的,在`node_modules`文件夹下就有,我也不知道什么原因
