### ISSUE TITLE
大神，为什么我弄得icon，刚添加文件的时候可以显示，但是清除缓存后就显示不出来了？

### ISSUE THREAD

**Issue by 649579742** [Plortinus/vue-multiple-pages#15]
大神，为什么我弄得icon，刚添加文件的时候可以显示，但是清除缓存后就显示不出来了？

**Comment by 649579742** [comment]
GET http://localhost:8010/fd2711f07151f242a69e5eabb6c1b1b5.ttf 
vue.runtime.esm.js?547b:7115 Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
vue.runtime.esm.js?547b:7125 You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
index.html:1 GET http://localhost:8010/47980f407ecd3490f023d05b4194de5f.woff

**Comment by 649579742** [comment]
我把字体文件的'cache-loader',注释掉就可以了，但是有没有其他方法解决？

**Comment by Plortinus** [comment]
是不是文件太大,超过了`url-loader`的限制了?

**Comment by 649579742** [comment]
都是22KB啊，我感觉是缓存那边的问题，因为我把缓存文件夹删除了就可以显示了，但是过一会儿清空缓存就又提示找不到文件了。

**Comment by Plortinus** [comment]
有可以复现的项目看吗?我这里试了一下没有出现这个问题[issue15](https://github.com/Plortinus/issues15)

**Comment by Plortinus** [comment]
最好提供一下详细一点的复现步骤,我的操作可能和你不一样.

**Comment by 649579742** [comment]
[测试项目](https://github.com/649579742/meiyimini) 刚用github还不太会用啊，这个是我的项目，然后我里面把字体文件的cache-loader注释掉了。。

**Comment by 649579742** [comment]
我看了你的项目，我说的icon是指iconFont之类的icon..

**Comment by Plortinus** [comment]
@649579742 我的项目也是iconfont,你看里面的login页面.
你的项目,我启用了cache-loader,然后npm run dev之后查看index页面,然后利用chrome浏览器上方的'清空缓存并硬性重新加载', 页面上的叹号图标还是在的,没有消失.
环境是Mac电脑 Chrome浏览器

**Comment by 649579742** [comment]
这么奇怪，我这启用了cache-loader清空缓存并硬性重新加载就报最上面2楼那个错了，字体文件404。。。不过我用的是Windows7

**Comment by Plortinus** [comment]
@649579742 2楼的那个错看不明白,你给控制台截图一下完整的错误吧

**Comment by 649579742** [comment]
![image](https://cloud.githubusercontent.com/assets/22883588/26441445/0653c27e-4163-11e7-9f48-e60660d2f3a6.png)

**Comment by Plortinus** [comment]
我用win10系统试了一下,没这个问题,`node`版本是`6.10.1`.Mac对应的`node`版本是`7.8.0`

**Comment by 649579742** [comment]
我node是6.10.0，难道是版本问题。。。

**Comment by Plortinus** [comment]
可以升级一下node版本试试

**Comment by Plortinus** [comment]
hold不住`cache-loader`,生产环境还是慎用的好,我去掉这个`cache-loader`了
