### ISSUE TITLE
css 修改后 浏览器显示  Nothing hot updated.

### ISSUE THREAD

**Issue by zuimeiaj** [Plortinus/vue-multiple-pages#17]

**Comment by Plortinus** [comment]
`css`用的是`extract-text-webpack-plugin`的`2.1.0`版本,不支持HMR,会在2.2的时候支持,[详情](https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/222)

**Comment by Nekojita1** [comment]
请问这个办法有解决方式吗 `extract-text-webpack-plugin` 升级到 `3.0.0` 版本了 同样还是 Nothing hot updated.

**Comment by Plortinus** [comment]
3.0.0里好像还是没有支持HMR,可以使用这个解决[css-hot-loader](https://github.com/shepherdwind/css-hot-loader)

**Comment by Nekojita1** [comment]
@Plortinus 谢谢！ 成功解决了！
