### ISSUE TITLE
修改显示的默认路径

### ISSUE THREAD

**Issue by Bimbaloo** [Plortinus/vue-multiple-pages#19]
感谢您的脚手架，有些疑问望解答。
![image](https://user-images.githubusercontent.com/17932133/27121161-bb6394b8-5118-11e7-998a-f7af24cc5aef.png)
1、如何修改显示的默认路径？
2、哪里能直接打开页面的配置吗？

**Comment by Plortinus** [comment]
这个东西是webpack-dev-server输出的,webpack-dev-server暂时没有你说的这种配置,所以说暂时解决不了

**Comment by Bimbaloo** [comment]
好的，谢谢。另有两个关于路由设置的问题请教：
1、请问怎么设置在浏览器输入http://127.0.0.1:8010以后，自动跳转至http://127.0.0.1:8010/search.html；
2、
![image](https://user-images.githubusercontent.com/17932133/27163340-4ce14822-51b9-11e7-86e6-6552bd1d92f9.png)
请问在哪里设置可以去除url中多余的'#'

**Comment by Plortinus** [comment]
1. 第一个问题没搞过
2. 第二个问题,你应该是用的vue-router吧,里面有个[History模式](http://router.vuejs.org/zh-cn/essentials/history-mode.html),不过得需要后端配合

**Comment by Plortinus** [comment]
@Bimbaloo 终于找到解决方法了，[webpack-dev-server 的两个配置项open和openPage](https://webpack.js.org/configuration/dev-server/#devserver-open)

**Comment by Bimbaloo** [comment]
非常感谢，您抽时间帮忙解决这个问题.当时对webpack近乎0了解，很多问题感觉无从下手，现在慢慢的有所了解，希望您的这个脚手架也能不断维护升级~~~再次感谢
