### ISSUE TITLE
Cannot read property call of undefined

### ISSUE THREAD

**Issue by BusyHe** [Plortinus/vue-multiple-pages#2]
想请教你个问题，我的也报这个错误，看到你sf的回答，我用的是vue-cil脚手架，不知道怎么改解决这个错误

**Comment by Plortinus** [comment]
@BusyHe 这种一般都是一些webpack插件的用法用错了会导致

**Comment by Plortinus** [comment]
可以去这里去寻找解决方法的灵感：[Uncaught TypeError: Cannot read property 'call' of undefined ](https://github.com/webpack/webpack/issues/959)

**Comment by BusyHe** [comment]
万分感谢！我研究一下

**Comment by BusyHe** [comment]
插件没用错，我生成的多页面，只要引用了第三方的ui组件，例如element-ui，mint-ui就会报错，就是只是引用，单页面是没有问题的

**Comment by Plortinus** [comment]
@BusyHe 推荐你用他们官方的starter试试[element-starter](https://github.com/ElementUI/element-starter) 对比一下配置，package包

**Comment by BusyHe** [comment]
我感觉我的多页买呢配置错误了，我用你的脚手架吧
