### ISSUE TITLE
Is it possible to make this also server-side ?

### ISSUE THREAD

**Issue by drupalshift** [Plortinus/vue-multiple-pages#20]
Hi 
First of all thanks for this awesome starter kit , really helped me <3
I was wondering is it possible to also render pages server side whenever javascript is not available !?

Thanks in advance

**Comment by Plortinus** [comment]
I have no experience on ssr,but the [issue11](https://github.com/Plortinus/vue-multiple-pages/issues/11) said this starter kit cannot used with ssr

**Comment by drupalshift** [comment]
:disappointed: Why not ? it's so useful , is there any technical issue or difficulty ? Do you know any multiple page kit like this that is Hybrid ( server-side & client-side ) !?

**Comment by nikoohp** [comment]
[https://nuxtjs.org/](url)

**Comment by Plortinus** [comment]
FYI [Vue-cli3 disable-index-generation](https://cli.vuejs.org/guide/html-and-static-assets.html#disable-index-generation)
