### ISSUE TITLE
无法使用vue-particles

### ISSUE THREAD

**Issue by elive777** [Plortinus/vue-multiple-pages#22]
我在SPA模版里能够使用vue-particles，但在这里，却是报错的。
![default](https://user-images.githubusercontent.com/8650177/28455478-c801e5fe-6e31-11e7-9d23-c9734bbf7a30.png)
这是还需要更改什么配置吗？

**Comment by elive777** [comment]
这里是SPA是指官方的 vue-cli 建立的模版

**Comment by elive777** [comment]
哦。这个后来我对比了下 发现是 少了 babel-preset-env 插件，但安装这个插件后 报错：
![default](https://user-images.githubusercontent.com/8650177/28456429-ddac2e34-6e34-11e7-9cc5-2de64fe635f5.png)
然后 命令行显示：
![default](https://user-images.githubusercontent.com/8650177/28456452-edfee8ee-6e34-11e7-8cb2-712743ffc938.png)
好像变成不压缩了？！

**Comment by elive777** [comment]
我去，终于可以了。后面这个是我调试的时候把 exclude: /node_modules/ 给注释了。
这个插件自动安装依赖的时候 没安装 babel-preset-env 还有其他关联的 baebl 才造成的。所以主要还是自己没搞清楚，我的错。

**Comment by Plortinus** [comment]
这个vue-particles还不太完善啊
