### ISSUE TITLE
关于css压缩和js压缩

### ISSUE THREAD

**Issue by Bimbaloo** [Plortinus/vue-multiple-pages#24]
![css](https://user-images.githubusercontent.com/17932133/29112892-eb57fddc-7d21-11e7-9e4e-4d95b66835a1.png)
![js](https://user-images.githubusercontent.com/17932133/29112899-f026e710-7d21-11e7-9883-826b6e20e411.png)

感谢您不断维护这个脚手架，使用中有些问题想向您请教：
npm run build之后编译出来的js和css文件都很大，但源文件也只有几百行的js，css就更少了，所以想问下您，是不是没有进行css和js的压缩，还是说有相关插件功能可能并没有被我启用？

![1](https://user-images.githubusercontent.com/17932133/29113905-17fc9958-7d25-11e7-8f2d-1d2275c11092.jpg)
这个首页几乎没有内容，但是加载的css和js就已经达到了5.4M。
想请教下您，该怎么样修改可以在npm run build的时候进行自动压缩(css和js)

**Comment by Plortinus** [comment]
有没有压缩，你打开dist目录下的js和css文件看看就知道了.我现在的项目打包出来的css和js都没有像你图上的那么夸张
npm run build 之后都挺小的，你可以发一下npm run build 之后终端里的图，看看webpack输出的信息。
实在不行的话，你可以在github上上传一个类似的项目（前提是不要泄露你们公司代码）复现一下

**Comment by Plortinus** [comment]
压缩的代码是在webpack.config.js的最后面：
```js
    new webpack.optimize.UglifyJsPlugin({
      compress: {
        warnings: false
      }
    })
```

**Comment by Plortinus** [comment]
找不到原因可以贴一下你的webpack.config.js看看

**Comment by Bimbaloo** [comment]
https://github.com/Bimbaloo/tracing/blob/backup/project/webpack.config.js
根据您之前版本的，只在昨天修改了自动打开页面@Plortinus 您看下

**Comment by Bimbaloo** [comment]
![1](https://user-images.githubusercontent.com/17932133/29116804-a09c9f02-7d2e-11e7-8a2a-5c3282bc61dd.png)
打开其中一个css,好像是没有压缩啊....

**Comment by Plortinus** [comment]
我看了一下这项目，npm run dev或者npm run build之后，终端里都有一些错，解决这些错之后应该会好一些。css文件太大可能是因为element-ui的css没有抽取出来导致的

**Comment by Bimbaloo** [comment]
你看到的错误应该是没有将gojs和element的替换或者是因为api无法连上的错误吧，api目前在局域网上.我这边项目是没有报错的。但是您说的`element-ui的css没有抽取出来导致的`这点我不是很明白，请您指点下 谢谢

**Comment by Plortinus** [comment]
我这个webpack的css配置是这样的：生成两个css文件，一个是vendors.css,这个是所有页面共享的css，还有个是当前页面独有的css。
你这个search.css之所以大，是因为里面包含里这个页面用到的所有的css，你看看文件就能发现里面有reset.css内容、elementui的css、还有common.less的css。
我看了一下所有页面的app.js发现wip_center下的app.js里没有引用elementui的css，就导致webpack认为这个elementui的css不是所有页面共享的，所以就生成到了各自页面的css中去了，reset.css common.less同理

**Comment by Bimbaloo** [comment]
仔细看了下您的commit记录，发现在2017/4/14有一次大的update,进过测试后发现在这个之前的版本的页面独有css是不会自动压缩的（npm run build）,在之后的版本是会有压缩这个功能的。因为使用这个脚手架较早，版本也比较老。现在的问题是一旦更新脚手架版本，项目需要改动的地方有点多（不确定的因素不较多），所以您能不能看下原来版本的问题，看下是不是某个配置造成的。  
                                                                                                               ---以上 感谢

**Comment by Plortinus** [comment]
你看这个[commit](https://github.com/Plortinus/vue-multiple-pages/commit/2cefd205fb999f731393939fe569f836896b6189)记录，加个插件，很清晰吧，直接在现有的webpack的配置文件里加就行

**Comment by Bimbaloo** [comment]
已经添加了这个插件，使用后发现效果好像微乎其微....
![11](https://user-images.githubusercontent.com/17932133/29267442-47ffdbc0-811b-11e7-8393-3366c0eae0d8.png)
不过还是很感谢

**Comment by Plortinus** [comment]
这应该是没生效吧，你打开看看css真的被压缩了吗？

**Comment by Bimbaloo** [comment]
看了，生效了....

**Comment by Bimbaloo** [comment]
![1](https://user-images.githubusercontent.com/17932133/29300945-82563db0-81ab-11e7-8277-47445b427201.png)
使用了您的新版本后发现一个问题：一旦在app.vue里面使用组件，就会报`Failed to mount component: template or render function not defined`错误。试了下您的模板，发现您的demo里面并没有嵌套组件。不知道这个是不是一个bug，能不能请您在demo里面添加一个实例

**Comment by Bimbaloo** [comment]
@Plortinus  能麻烦您在最新版中有一个使用组件的demo吗

**Comment by Plortinus** [comment]
components 文件夹里不是有个modal.vue吗？

**Comment by Bimbaloo** [comment]
![1](https://user-images.githubusercontent.com/17932133/29393363-db193e1c-8335-11e7-9468-95684586ab03.png)

是的，但是你的demo里面只是在页面里面import了这个modal.vue，并没有去使用，一旦使用就会出现之前图片的报错。所以希望您这边能做一个使用的demo。

**Comment by Plortinus** [comment]
你的modal组件写的有问题吧，我这样写modal.vue就没问题：
```js
<template lang="html">
  <el-card class="login-card">
    <div slot="header">
      <span class="logo-text">Management System</span>
    </div>
    <div class="">
      嵌套组件
    </div>
  </el-card>
</template>

<script>
  export default {
  }
</script>

<style lang="css">
  .modal {
    width: 100px;
    height: 100px;
    border: 1px solid #ccc;
  }
</style>
```
![123](https://user-images.githubusercontent.com/20693993/29393607-57d453f0-8337-11e7-9545-015b061f9c90.png)

**Comment by Bimbaloo** [comment]
我是发现组件引入并渲染后会报这个错。于是去你的demo看，你的demo里面import了这个modal.vue，但是没有渲染，我试着渲染发现也会报同样的错。
![1](https://user-images.githubusercontent.com/17932133/29393890-420819c4-8339-11e7-84cf-b545bdffb3d8.png)---这是你demo里面未渲染的.
![image](https://user-images.githubusercontent.com/17932133/29393920-8c36f060-8339-11e7-9a85-1412fdee03a0.png)---这是我在你的demo里面试着去渲染的。所以我不知道是bug还是哪里处理错。@Plortinus

**Comment by Plortinus** [comment]
用最新版的代码试试，或者你升级一下elementui 和vue,或者你上传一下你这个项目，我自己试着是没问题.

**Comment by Bimbaloo** [comment]
解决了，是webpack版本问题。 谢谢
