### ISSUE TITLE
Vue Devtools无法使用？

### ISSUE THREAD

**Issue by xiongsyao** [Plortinus/vue-multiple-pages#25]
`npm run dev` 后Vue Devtools提示模式是生产模式，无法使用.这样不方便管理`vuex`，有没有解决的办法呢?

**Comment by xiongsyao** [comment]
已经解决了，在app.js中加上`Vue.config.devtools = true`，然后在谷歌插件管理界面chrome://extensions/勾选上允许访问文件网址就可以了。

**Comment by Plortinus** [comment]
我这里app.js不需要加代码就有vue devtool，你去掉试一下
