### ISSUE TITLE
Question concerning creation of new folder/pages

### ISSUE THREAD

**Issue by Kiganjo** [Plortinus/vue-multiple-pages#26]
Hi ! First of all thanks for this awsome work !
I have a question concerning the creation of new pasges , i follow your pattern : folder + inside 3 different files all name app.(html/js/vue) but when i try to reach my new page that crash and it's impossible to reach the page ! So i just want to know if it's possible to create new pages and if we can what i'm doing wrong ?
Thanks !

**Comment by Plortinus** [comment]
After you created new pages,you should re-execute this command `npm run dev`.

**Comment by Kiganjo** [comment]
ohhhhh !! I dont even think about it ! Thx !
