### ISSUE TITLE
这种多个app.js的如何引入babel-polyfill？

### ISSUE THREAD

**Issue by 649579742** [Plortinus/vue-multiple-pages#27]
需要引入babel-polyfill解决axios在IE9的问题，但是这种多个app.js的不知道如何解决。。。

**Comment by Plortinus** [comment]
项目中，我都是写一个单独axios封装`axios.js`来统一拦截ajax请求，然后每个vue文件里引入这个`axios.js`

大概是这个模样：
```js
import axios from 'axios'
import 'babel-polyfill'

import { MessageBox } from 'element-ui'

export default function (data) {
  if (data.params) {
    data.params.timeStamp = new Date().getTime()
  } else {
    data.params = {
      timeStamp: new Date().getTime()
    }
  }
  data.headers = {
    'uid': localStorage.getItem('uid') || '',
    'accessToken': localStorage.getItem('accessToken') || ''
  }
  return axios(data).catch(error => {
    switch (error.response.status) {
      case 456:
        data.params = {}
        MessageBox.alert('登录已失效，点击确定重新登录', '提示', {
          confirmButtonText: '确定',
          callback: action => {
            location.href = '../user/login.html'
          }
        })
        break
      case 567:
        MessageBox.alert('登录已失效，点击确定重新登录', '提示', {
          confirmButtonText: '确定',
          callback: action => {
            location.href = '../user/login.html'
          }
        })
        break
      case 401:
        location.href = '../user/login.html'
        break
      case 403:
        MessageBox.alert('您没有操作权限')
        break
      case 404:
        MessageBox.alert('您访问的资源不存在')
        break
      case 405:
        MessageBox.alert('服务器内部错误405')
        break
      case 500:
        MessageBox.alert('服务器内部错误500')
        break
    }
  })
}

```

**Comment by 649579742** [comment]
我刚去试了下，res全是undefined，但是我在IE控制台里面看能看到服务器返回的json。。

**Comment by 649579742** [comment]
import axios from 'axios';
import 'babel-polyfill';
var oproto = Object.prototype;
var serialize = oproto.toString;
var Rxports = {
	/**
	  * 封装axios，减少学习成本，参数基本跟jq ajax一致
	  * @param {String} type			请求的类型，默认post
	  * @param {String} url				请求地址
	  * @param {String} time			超时时间
	  * @param {Object} data			请求参数
	  * @param {String} dataType		预期服务器返回的数据类型，xml html json ...
	  * @param {Object} headers			自定义请求headers
	  * @param {Function} success		请求成功后，这里会有两个参数,服务器返回数据，返回状态，[data, res]
	  * @param {Function} error		发送请求前
	  * @param return
	*/
	ajax:function (opt){
		var opts = opt || {};
		if (!opts.url) {
			alert('请填写接口地址');
			return false;
		}
		axios({
			method: opts.type || 'post',
			url: opts.url,
			params: opts.data || {},
			headers: opts.headers || {
			  	'Content-Type':'application/x-www-form-urlencoded'
			},
			// `baseURL` 将自动加在 `url` 前面，除非 `url` 是一个绝对 URL。
  			// 它可以通过设置一个 `baseURL` 便于为 axios 实例的方法传递相对 URL
			//baseURL:'http://'+location.host,
			baseURL:'/api',
			//baseURL:'http://www.meiyi.ai',
			timeout: opts.time || 10*100000,
			responseType: opts.dataType || 'json',
			data:opts.data2||{},
		}).then(res => {
			if(res.status == 200 ){
				if(opts.success){
					opts.success(res.data,res);
				}
			}else{
				if (data.error) {
					opts.error(res);
				}else{
					console.log('好多人在访问呀，请重新试试[timeout]');
				}
			}
		}).catch(function (error){
			console.log(error);
			if (opts.error) {
				opts.error(error);
			}else{
				console.log('好多人在访问呀，请重新试试[timeout]');
			}
		});
	},
}
export default Rxports;

我是这么搞。。

**Comment by 649579742** [comment]
```
我是这么搞的。。。

import axios from 'axios';
import 'babel-polyfill';
var oproto = Object.prototype;
var serialize = oproto.toString;
var Rxports = {
	ajax:function (opt){
		var opts = opt || {};
		if (!opts.url) {
			alert('请填写接口地址');
			return false;
		}
		axios({
			method: opts.type || 'post',
			url: opts.url,
			params: opts.data || {},
			headers: opts.headers || {
			  	'Content-Type':'application/x-www-form-urlencoded'
			},
			//baseURL:'http://'+location.host,
			baseURL:'/api',
			//baseURL:'http://www.meiyi.ai',
			timeout: opts.time || 10*100000,
			responseType: opts.dataType || 'json',
			data:opts.data2||{},
		}).then(res => {
			if(res.status == 200 ){
				if(opts.success){
					opts.success(res.data,res);
				}
			}else{
				if (data.error) {
					opts.error(res);
				}else{
					console.log('好多人在访问呀，请重新试试[timeout]');
				}
			}
		}).catch(function (error){
			console.log(error);
			if (opts.error) {
				opts.error(error);
			}else{
				console.log('好多人在访问呀，请重新试试[timeout]');
			}
		});
	},
}
export default Rxports;
```
