### ISSUE TITLE
新建一个页面后，需要重新 npm run dev

### ISSUE THREAD

**Issue by PichurChill** [Plortinus/vue-multiple-pages#29]
新建一个页面的文件夹后，访问对应的页面是 Cannot GET 请问如何配置才能避免重新  run dev

**Comment by Plortinus** [comment]
目前还没有找到好的解决办法，因为npm run dev之后入口文件有哪些都是固定好了，入口文件检测只在npm run dev的一瞬间。

**Comment by PichurChill** [comment]
谢谢，我也去研究研究

**Comment by xiangsongtao** [comment]
我认为的方案:
1. 做之前把添加的路径做好
2. 或者, webpack配置文件修改后自动重新run dev
