### ISSUE TITLE
请教个问题

### ISSUE THREAD

**Issue by lizhoukai** [Plortinus/vue-multiple-pages#3]
localhost:8080/user/ 这个域名 默认能不能指向某个区块 
比如 localhost:8080/user/ 这区块 我想默认设置为首页，访问域名为localhost:8080，后面没有参数 user 参数

**Comment by Plortinus** [comment]
设置这些区块默认的首页，只有在单页应用里或者是网站后台的nginx配置什么的才能实现，我这个脚手架无法实现这样的功能

**Comment by Plortinus** [comment]
你说的这个应该是关于“路由”的东西吧

**Comment by liSNS** [comment]
谢谢 是这样啊 我想部分用路由控制页面跳转，部分使用静态多页面href
