### ISSUE TITLE
请问一下打包完成触发回调执行一段代码？

### ISSUE THREAD

**Issue by lanshengzhong** [Plortinus/vue-multiple-pages#30]
因为有需求打包完成后复制dist文件夹到其它目录下，不知道怎么做呢？

**Comment by Plortinus** [comment]
改改配置，直接打包到需要copy到的那个目录不就可以了吗？或者试试[copy-webpack-plugin](https://github.com/webpack-contrib/copy-webpack-plugin)

**Comment by lanshengzhong** [comment]
嗯 第一种方案考虑过是可以的直接改输出的目录，不过考虑需求还是希望本目录下有一份dist  另外目录也需要一份 ，copy-webpack-plugin 和我写的本质都是一样的   不过复制是需要等编译完成后才执行

`
// setTimeout(()=> {
//   let bb = ora('正在复制文件夹...').start()
//   let cppath = resolve(__dirname, '../../../hzhui_app/widget/dist')
//   rm(join(cppath, 'widget'), err => {
//     if (err) throw console.warn(err)
//     shell.cp('-Rf', join(resolve(__dirname, ''), './dist'), cppath);
//     console.log('复制完成')
//     bb.stop()
//   })
`
先关闭咯  暂时先用第一种吧  后续再看看先
