### ISSUE TITLE
启动项目成功后，无法通过ip访问。localhost和127.0.0.1可以访问

### ISSUE THREAD

**Issue by Bimbaloo** [Plortinus/vue-multiple-pages#31]
启动项目成功后，无法通过ip访问。localhost和127.0.0.1可以访问。请问这是什么原因，需要修改哪个配置？

**Comment by Bimbaloo** [comment]
已解决：webpack.config.js下的devServer.host修改为“0.0.0.0”即可

**Comment by Bimbaloo** [comment]
还是有问题，如果修改devServer.host修改为“0.0.0.0”，那么openPage就会出错，自动拼接前面的0.0.0.0作为ip
![image](https://user-images.githubusercontent.com/17932133/31878445-b29fdbba-b80c-11e7-8f46-ed91d8c7a89f.png)

**Comment by Bimbaloo** [comment]
![2 1](https://user-images.githubusercontent.com/17932133/31879964-a434b2e4-b811-11e7-958a-66f72a72dca7.jpg)
https://doc.webpack-china.org/configuration/dev-server/#devserver-uselocalip
这个属性可以勉强解决这个问题，但是还是不是很完美。

**Comment by Plortinus** [comment]
试了一下。
1. 先把`webpack-dev-server`升级到2.9.3版本。
2. 然后修改webpack.config.js，将host改为`0.0.0.0`，这时候运行`npm run dev`,打开的是`http://0.0.0.0:8010/user/login.html`页面，换成本地ip/localhost/127.0.0.1都可以访问。
3. 若是在package.json里在dev命令添加`--useLocalIp`,运行之后打开的是`http://本地ip:8010/user/login.html`页面，换成本地ip/localhost/127.0.0.1都可以访问。

这是github上的问题链接https://github.com/webpack/webpack-dev-server/issues/147

完美的解决方案的话，得用用`webpack-dev-server-middleware`,参考https://github.com/vuejs-templates/webpack/blob/develop/template/build/dev-server.js

得研究一下解决

**Comment by xm66778899** [comment]
webpack-dev-serve version  2.11.1
一个解决办法是，直接修改/node_modules/webpack-dev-server/bin/webpack-dev-server.js
  if (argv.host !== 'localhost' || !options.host) { options.host = argv.host; }
  options.host='0.0.0.0'   //新增的一行。

**Comment by zhanyuzhang** [comment]
我说的IP不是127.0.0.1，而是路由器分配给我的IP，比如10.255.206.118这样的IP，依旧不能打开 呀

**Comment by Plortinus** [comment]
新的架构可以用ip访问
