### ISSUE TITLE
如果想引用公共的css文件应该怎么操作？

### ISSUE THREAD

**Issue by heheda11** [Plortinus/vue-multiple-pages#32]
在assets/css下建了一个common文件夹，里面有个common.scss的文件，比如login/app.html要用到它，应该怎么引用？该怎么写？求解，多谢

**Comment by Plortinus** [comment]
在app.js里import进来即可

**Comment by heheda11** [comment]
好的谢谢，我想在组件.vue的文件里面写sass，<style lang="scss">这里包起来，但编译总是报错，通不过，package.json里面已经放了"node-sass": "^4.5.3",这是什么原因呢？

**Comment by Plortinus** [comment]
cli构建的时候有选择scss那一项吧，选了之后会在webpack的配置文件里添加scss的处理代码。难道没生效？

**Comment by heheda11** [comment]
有选scss那一项目，webpack rules里面有scss的相关的东西
options: {
          loaders: {
            css: ['css-hot-loader'].concat(ExtractTextPlugin.extract({
              use: 'css-loader',
              fallback: 'style-loader'
            })),
            less: ['css-hot-loader'].concat(ExtractTextPlugin.extract({
              use: ['css-loader', 'postcss-loader', 'less-loader'],
              fallback: 'style-loader'
            })),
            scss: ['css-hot-loader'].concat(ExtractTextPlugin.extract({
              use: ['sass-loader','css-loader', 'postcss-loader' ],
              fallback: 'style-loader'
            })),
            postcss: ['css-hot-loader'].concat(ExtractTextPlugin.extract({
              use: ['css-loader', 'postcss-loader'],
              fallback: 'style-loader'
            }))
          }
        }


{
        test: /\.scss$/,
        use: ['css-hot-loader'].concat(ExtractTextPlugin.extract({
          use: ['css-loader', 'postcss-loader', 'sass-loader'],
          fallback: 'style-loader'
        }))
      },

**Comment by Plortinus** [comment]
我试了一下没啥问题。你重新npm install一下或者检查一下你写的scss语法有没有错。
