### ISSUE TITLE
请问一下要配置开发环境、测试环境、生产环境的接口请求url，该怎么配置？

### ISSUE THREAD

**Issue by heheda11** [Plortinus/vue-multiple-pages#33]
要配置开发环境、测试环境、生产环境的接口请求url，该怎么配置？

**Comment by Plortinus** [comment]
webpack的proxy属性，可以查一下这个的属性的用法。我的项目设置类似于这样的
```js
    proxy: {
      '/api': {
        target: 'http://www.baidu.com/api',
        changeOrigin: true,
        pathRewrite: { '^/api': '' }
      }
    },
```

**Comment by heheda11** [comment]
我想知道的是如何设置不同的环境请求接口的baseUrl,应该不是这个proxy吧，下面这三个环境每个环境如何对应一个请求接口的baseUrl?
"dev": "cross-env NODE_ENV=development webpack-dev-server --inline --hot",
    "test": "cross-env NODE_ENV=test webpack --progress --hide-modules",
    "build": "cross-env NODE_ENV=production webpack --progress --hide-modules"

**Comment by Plortinus** [comment]
先定义个对象,例如：
```js
var baseUrl = {
  'development': 'https://www.baidu.com/dev',
  'test': 'https://www.baidu.com/test',
  'production': 'https://www.baidu.com/production'
}
```
然后改proxy下面的target为
```js
target: baseUrl[process.env.NODE_ENV]
```
