### ISSUE TITLE
打包后css文件里引用的图片路径不对

### ISSUE THREAD

**Issue by heheda11** [Plortinus/vue-multiple-pages#34]
Sass文件里这样引用：例如：background: url('../../img/bg.png') no-repeat bottom center;
打包后的结果：background:url(assets/img/bg.f0d3576.png)
放到服务器上部署后，就变成了根目录+/assets/css/assets/img/bg.f0d3576.png，多了个/assets/css，所以背景图样式出不来了
这个问题是webpack哪个地方设置的不对吗？

**Comment by Plortinus** [comment]
webpack不好处理css里的背景图，建议import进来处理
