### ISSUE TITLE
一已解决

### ISSUE THREAD

**Issue by tonyjiafan** [Plortinus/vue-multiple-pages#36]
请教一下作者， 我想在你这个基础上把对应模块的静态资源 img、css 全部打包到对应的文件夹，我发布的时候就需要提取一个文件夹。

**Comment by Plortinus** [comment]
看不太懂你的意思，请举例说明一下

**Comment by tonyjiafan** [comment]
现在的dist目录是 assets 然后是对应的模块文件 想把assets里面的user模块的图片和js和样式都打包到user目录下和user目录下的login.html、index.html文件放在一起
