### ISSUE TITLE
如何引入公共的样式或js?

### ISSUE THREAD

**Issue by pangao66** [Plortinus/vue-multiple-pages#38]
如果在每个页面都引入一段相同的css 或js代码?   在每个页面 的app.js里面引入每次都要写一遍.
  以及html里面如何引入静态文件? 目前html里面用link或者script标签方式引入都路径不对 ,vue-cli那样可以直接在index.html里面引入static目录下的文件.

**Comment by AlanSean** [comment]
下载 并配置 copy-webpack-plugin
就可以了写link或者script引入的时候写绝对路径（看你如何配置了）

**Comment by Plortinus** [comment]
项目中，我都是建好一个文件目录，然后无限复制，这样就变相的引入公共样式...

**Comment by AlanSean** [comment]
你是直接在page里面写了一个css文件夹l来进行引用？

**Comment by Plortinus** [comment]
公共样式文件我是写在assets目录下，然后在app.js里引用

**Comment by AlanSean** [comment]
我现在遇到的问题就是
     link问题     html里面写了link引入assets里面清除默认样式的文件  ExtractTextPlugin会报错   
很搞不懂 我已经copy了  难道ExtractTextPlugin也需要设置忽略某些文件吗 刚研究第三天 很揪心

**Comment by AlanSean** [comment]
现在又遇到的问题  我只写了一个html  vue js 文件 然后打包会Cannot read property 'call' of undefined
这是为啥  是因为CommonsChunkPlugin   必须两个页面以上才可以吗 但是在线运行是没问题的

**Comment by pangao66** [comment]
我是想直接在html里面引入  有的东西不能用webpack 模块化的不能在app.js里面引入. 能否提供一个vue-cli那样的static目录, vue-cli就是可以直接在index.html里面引入的
