### ISSUE TITLE
每次改了vue里面的js，就会报这个错，重新刷新才行

### ISSUE THREAD

**Issue by lyseky** [Plortinus/vue-multiple-pages#41]
[Vue warn]: Cannot find element: #app

**Comment by Plortinus** [comment]
在github上建个可复现这个问题的项目贴一下，我这里没有发现这个问题

**Comment by lyseky** [comment]
@Plortinus 好，周末我整理一下，这个项目好像没有自动es6转es5吧

**Comment by Plortinus** [comment]
用了babel转es6

**Comment by lyseky** [comment]
@Plortinus 我自己解决了，要加载完才能执行实例
window.onload = function () {
    var main = new Vue({
        el: '#main',
        data: {
            currentActivity: 'home'
        }
    });
}

**Comment by Plortinus** [comment]
感觉不需要这样hack，一定是其他某个地方的问题导致的
