### ISSUE TITLE
git显示每次打包hash值都变化，而公共文件没改过

### ISSUE THREAD

**Issue by lyseky** [Plortinus/vue-multiple-pages#44]
每次修改提交都会重新生成hash值，不能有效利用缓存，改过的hash才变比较好吧     

-<link rel="shortcut icon" href="/favicon.ico"><link href="/assets/css/vendors.css?cbd0e4a50b3e39ce4fd3" rel="stylesheet"><link href="/assets/css/cart.css?cbd0e4a50b3e39ce4fd3" rel="stylesheet"></head>
+<link rel="shortcut icon" href="/favicon.ico"><link href="/assets/css/vendors.css?516a5d7b8fcf0b8548f3" rel="stylesheet"><link href="/assets/css/cart.css?516a5d7b8fcf0b8548f3" rel="stylesheet"></head>
 <body>
 <div id="app"></div>
-<script type="text/javascript" src="/assets/js/vendors.js?cbd0e4a50b3e39ce4fd3"></script><script type="text/javascript" src="/assets/js/cart.js?cbd0e4a50b3e39ce4fd3"></script></body>
+<script type="text/javascript" src="/assets/js/vendors.js?516a5d7b8fcf0b8548f3"></script><script type="text/javascript" src="/assets/js/cart.js?516a5d7b8fcf0b8548f3"></script></body>
 </html>

**Comment by Plortinus** [comment]
我这边写的项目里，dist目录都没有加入到git上去，所以没这个问题

**Comment by lyseky** [comment]
@Plortinus 在服务器npm run build就没有这个问题？

**Comment by Plortinus** [comment]
说的有些误解，实际是有这个问题，hash通过htmlwebpackplugin插件上加的
