### ISSUE TITLE
一个组件的问题引发的相对路径问题

### ISSUE THREAD

**Issue by lyseky** [Plortinus/vue-multiple-pages#46]
我写了应该侧边栏组件，里面的路径都是用相对路径，然后在各个页面调用，但是用相对路径就会出现链接不对的问题，请问你是如何写子组件里面的url路径呢
              `<ul>
                    <li><a href="../index.html"><i class="home"></i>Homepage</a></li>
                    <li><a href="./search.html"><i class="search"></i>Search</a></li>
                    <li><a href="./category.html"><i class="categroy"></i>Category</a></li>
                    <li><a href="javascript:void(0);"><i class="message"></i>Message<sup></sup></a>
                   </li>
                    <li><a href="./cart.html"><i class="cart"></i>Cart<sup></sup></a></li>
                    <li><a href="./member.html"><i class="member"></i>My account</a></li>
                </ul>`

**Comment by lyseky** [comment]
我用js写成绝对路径解决了

**Comment by lyseky** [comment]
有没有好的解决方法呢，每次都要用js改成绝对路径

**Comment by Plortinus** [comment]
我这里是用得相对路径写的
