### ISSUE TITLE
我现在用的这一套打包，请求接口是用的fetch，但在部分移动端浏览器上报fetch is not defined,你们有谁遇到过吗？

### ISSUE THREAD

**Issue by heheda11** [Plortinus/vue-multiple-pages#47]
我现在用的这一套打包，请求接口是用的fetch，但在部分移动端浏览器上报fetch is not defined,你们有谁遇到过吗？求解决方案

**Comment by Plortinus** [comment]
没使用过fetch，推荐试一下这篇[博客](https://github.com/camsong/blog/issues/2)说的[es6-promise](https://github.com/stefanpenner/es6-promise)
