### ISSUE TITLE
页面做多了，每次运行都要等好久，有没有优化方案

### ISSUE THREAD

**Issue by lyseky** [Plortinus/vue-multiple-pages#48]

**Comment by holdfuture** [comment]
我也是啊，老铁，我70多个页面，马丹，开发模式简直没法用，等死人

**Comment by Plortinus** [comment]
我测试了一下，74个页面，npm run dev用了39s，你们多少页面用了多少秒？

**Comment by holdfuture** [comment]
我比你多，估计有接近100，关键是我改动一个文字，居然也要我等20秒，我还是自己想了N多办法优化了，如果直接生产打包，那估计更久，没个几分钟打不完，主要是dev模式下，这性能实在让我蛋疼，刚开始我没优化，直接等90秒，主要还有自己的一些组件，第三方插件等等，这都要耗性能

**Comment by Plortinus** [comment]
可以试试multipage-webpack-plugin这个webpack多页插件，配置代码示例看我提交的commit，感觉是优化了一部分

**Comment by lanshengzhong** [comment]
老铁们 我也是 要崩溃了啊

**Comment by Plortinus** [comment]
@lanshengzhong 试试我新改的webpack配置

**Comment by lyseky** [comment]
也是几十秒啊，后面我换了happypack打包快一点

**Comment by zhilianbi520** [comment]
@lyseky happypack怎么添加啊。打算用这个脚手架做多spa单页面应用整合的，好几百个页面的怎么破。

**Comment by Plortinus** [comment]
试试官方的pages设置，如果慢，给尤雨溪大佬提issue
