### ISSUE TITLE
请问如何加入scss的解析器？

### ISSUE THREAD

**Issue by csdudu** [Plortinus/vue-multiple-pages#5]
我想支持Vue组件中的<style lang="scss">代码段，请赐教！

**Comment by Plortinus** [comment]
新建了一个`scss`分支，你拉一下这个分支的代码试试看，我是这样改的：
<img width="414" alt="scss" src="https://cloud.githubusercontent.com/assets/20693993/22775876/84850978-eee8-11e6-8638-f44bc8cad814.png">
