### ISSUE TITLE
npm run build后，访问页面报错 Uncaught TypeError: Cannot read property 'call' of undefined  

### ISSUE THREAD

**Issue by heheda11** [Plortinus/vue-multiple-pages#52]
npm run dev运行时没有问题，页面正常
npm run build后，把文件部署到服务器后访问
页面报错：
bootstrap 5b33aa4de914b7683ee6:54 Uncaught TypeError: Cannot read property 'call' of undefined
    at e (bootstrap 5b33aa4de914b7683ee6:54)
    at window.webpackJsonp (bootstrap 5b33aa4de914b7683ee6:25)
 请问有谁知道怎么解决吗？

**Comment by Plortinus** [comment]
需要提供一个小demo复现一下
