### ISSUE TITLE
多页面如何进行拦截进入需要登录的页面呢

### ISSUE THREAD

**Issue by lyseky** [Plortinus/vue-multiple-pages#53]
比如a页面点击跳转到b页面，需要在a页面点击动作就要拦截进入b页面了，楼主是如何解决的

**Comment by Plortinus** [comment]
在common.js里写一个专门跳转页面的函数,参数就是当前a页面地址和b页面地址,然后在这个函数里对不同的地址进行拦截

**Comment by lyseky** [comment]
也是本地写死，不过一般都是通过请求接口来判断是否需要登录

**Comment by Plortinus** [comment]
判断特殊页面或者特殊规则,代码里有些地方一定是写死的.请求接口判断的话,就拦截请求吧
