### ISSUE TITLE
打包后  都是绝对路径

### ISSUE THREAD

**Issue by slyang520** [Plortinus/vue-multiple-pages#54]
打包后  都是绝对路径  js css 
文件本地无法打开的

**Comment by Plortinus** [comment]
你可以设置publicPath成`'./'`

**Comment by slyang520** [comment]
@Plortinus   只有一级页面才可以比如/index.html    有二级页面  这样是不行的   比如   /user/hello.html

**Comment by Plortinus** [comment]
应该是'`../'` 不是`'./'`

**Comment by slyang520** [comment]
@Plortinus  还是不行的 ，  你可以试一下    ../无法打开  ./只能打开一级页面

**Comment by Plortinus** [comment]
我试着可以啊……

**Comment by slyang520** [comment]
好吧。 确实不可以   我想其他的办法了 。。

**Comment by heheda11** [comment]
> 应该是'`../'` 不是`'./'`

请问一下，如果要支持多级目录的话可以怎么改造呢，现在的项目里面可能有一级的，两级的还是三级的，不知道该如何写那个publicPath，打包后放到服务器上，二级和三级的页面就访问不到js和css文件了，只有一级页面的才可以

**Comment by duanmw** [comment]
> > 应该是'`../'` 不是`'./'`
> 
> 请问一下，如果要支持多级目录的话可以怎么改造呢，现在的项目里面可能有一级的，两级的还是三级的，不知道该如何写那个publicPath，打包后放到服务器上，二级和三级的页面就访问不到js和css文件了，只有一级页面的才可以

我也有同样的问题
