### ISSUE TITLE
有这种可能么

### ISSUE THREAD

**Issue by sknightq** [Plortinus/vue-multiple-pages#55]
现在不是做了多个入口了么，能不能对每个路口再做vue-router？
比如目前的/pages/user下有个入口，然后login和index用vue-router去实现？

**Comment by Plortinus** [comment]
可以的,其实这就是一个多个单页组成的多页系统,每个页面里都可以做成一个单页应用

**Comment by sknightq** [comment]
我差不多实现了[Demo](http://www.sknight.cn:83/#/)
