### ISSUE TITLE
postcss初始化提示错误信息

### ISSUE THREAD

**Issue by lanshengzhong** [Plortinus/vue-multiple-pages#56]
![image](https://user-images.githubusercontent.com/20151096/38464171-74ea7250-3b3b-11e8-99f8-d0cf7a5468ed.png)

`Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js!node_modules/vue-loader/lib/style-compiler/index.js?{"optionsId":"0","vue":true,"scoped":false,"sourceMap":true}!node_modules/postcss-loader/lib/index.js!node_modules/vue-loader/lib/selector.js?type=styles&index=0!src/pages/user/login/app.vue:
    Entrypoint undefined = extract-text-webpack-plugin-output-filename
    [./node_modules/css-loader/index.js!./node_modules/vue-loader/lib/style-compiler/index.js?{"optionsId":"0","vue":true,"scoped":false,"sourceMap":true}!./node_modules/postcss-loader/lib/index.js!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./src/pages/user/login/app.vue] ./node_modules/css-loader!./node_modules/vue-loader/lib/style-compiler?{"optionsId":"0","vue":true,"scoped":false,"sourceMap":true}!./node_modules/postcss-loader/lib!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./src/pages/user/login/app.vue 371 bytes {0} [built] [1 warning]
    [./node_modules/css-loader/lib/css-base.js] 2.21 KiB {0} [built]

    WARNING in ./src/pages/user/login/app.vue (./node_modules/css-loader!./node_modules/vue-loader/lib/style-compiler?{"optionsId":"0","vue":true,"scoped":false,"sourceMap":true}!./node_modules/postcss-loader/lib!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./src/pages/user/login/app.vue)
    (Emitted value instead of an instance of Error)

     ⚠️  PostCSS Loader

    Previous source map found, but options.sourceMap isn't set.
    In this case the loader will discard the source map entirely for performance reasons.
    See https://github.com/postcss/postcss-loader#sourcemap for more information.
`

**Comment by Plortinus** [comment]
感谢提醒,已修复
