### ISSUE TITLE
postcss没有编译

### ISSUE THREAD

**Issue by ryanyeungzy** [Plortinus/vue-multiple-pages#58]
我尝试在*.vue文件中用以下语法：
<style lang="postcss">
  $text_color: #232323;
  #app {
    background: $text_color;
  }
</style>
发现没有执行过编译，请问如何可以应用上呢？

**Comment by Plortinus** [comment]
你试试我刚提交的commit的写法

**Comment by ryanyeungzy** [comment]
试过，还是没有效果。

**Comment by Plortinus** [comment]
postcss里你是怎么设置的？postcss本身没有语法，你这写法是别的css预处理器的语法吧

**Comment by ryanyeungzy** [comment]
明白了，我用scss就可以了
