### ISSUE TITLE
为什么不支持 es6 语法

### ISSUE THREAD

**Issue by ryanyeungzy** [Plortinus/vue-multiple-pages#59]
能否可以增加对 es6 语法的支持

**Comment by Plortinus** [comment]
支持啊,哪个语法不行?

**Comment by ryanyeungzy** [comment]
三个点语法不支持：
 Unexpected token (13:6)
  11 | const messages = {
  12 |     en: {
> 13 |       ...enLocale,
     |       ^
  14 |       ...elementEnLocale
  15 |     },
  16 |     zh: {`

**Comment by Plortinus** [comment]
bable默认用了es2015,没用stage2,我得改一下

**Comment by Plortinus** [comment]
`.babelrc`文件改成这样即可:
```json
{
  "presets": [
    ["env", { "modules": false }],
    "stage-2"
  ]
}
```

**Comment by juanapu** [comment]
css import 引入会报错，改require就行了。 js es6语法是支持的
