### ISSUE TITLE
mint-ui里的css文件加载不了

### ISSUE THREAD

**Issue by TOBOM** [Plortinus/vue-multiple-pages#6]
import 'element-ui/lib/theme-default/index.css'
import 'mint-ui/lib/style.min.css'
同样的方法element能加载出样式,mint-ui无法加载

**Comment by Plortinus** [comment]
`mint-ui`是这样引入的`import 'mint-ui/lib/style.css'`
[看官网文档](http://mint-ui.github.io/docs/#!/zh-cn2/quickstart)

**Comment by TOBOM** [comment]
已成功,可能是npm i下载问题
