### ISSUE TITLE
如何使用vue-router 是否可以提供一个例子？

### ISSUE THREAD

**Issue by byoungd** [Plortinus/vue-multiple-pages#63]
尝试加入vue-router时 不知道路径究竟是怎样的
例子里登录页的地址为
`
/user/login.html

`
配置了Vue-router  hash模式下可以用，路径会变成下面这样
`
/user/login.html#/

`

如果使用history模式， 具体的路径是怎样呢？

尝试了 `
/user/hello 或 /user/login.html/hello
`

都会显示 cannot GET 

所以是否需要配置 base，以及如何配置还望给个说明
---

感谢！

**Comment by zhilianbi520** [comment]
同问在history模式下怎么弄。。

**Comment by Plortinus** [comment]
用vue router的话推荐使用官方cli生成的单页应用

**Comment by swoiow** [comment]
test

**Comment by swoiow** [comment]
@Plortinus 

> 用vue router的话推荐使用官方cli生成的单页应用

这个回复建议，加在 Readme 里面，当我用框架写完四五个页面，准备组合起来的时候，想配vue router，十分难搞

**Comment by zhilianbi520** [comment]
@Plortinus  想把这个脚手架作为多个单页面系统的整合。。。就是现在的页面作为spa单页面的入口，这样实现合理嘛？

**Comment by Plortinus** [comment]
@zhilianbi520 可以这么搞，在每个页面的目录里添加router相关的代码，在app.js里`new Vue()`的时候加进去即可

**Comment by Plortinus** [comment]
@swoiow 加router不难搞啊，每个页面算是一个单页应用，照着官网写就是了

**Comment by zhilianbi520** [comment]
@Plortinus  收到， 多谢。尝试了下，可以。
