### ISSUE TITLE
extract-text-webpack-plugin应该被替换成mini-css-extract-plugin

### ISSUE THREAD

**Issue by yangchendoit** [Plortinus/vue-multiple-pages#65]
<img width="464" alt="_20180720113524" src="https://user-images.githubusercontent.com/27750211/42981859-0e597546-8c11-11e8-9179-837a18de4cd8.png">

[extract-text-webpack-plugin](https://github.com/webpack-contrib/extract-text-webpack-plugin) 的readme有提到

**Comment by lyseky** [comment]
替换有效嘛？
