### ISSUE TITLE
npm run dev 验证表单报错

### ISSUE THREAD

**Issue by yuanshengchao** [Plortinus/vue-multiple-pages#67]
在dev模式下，运行elementui的form验证直接报错哇，如何解决呀

**Comment by yuanshengchao** [comment]
报错信息为：
vue.runtime.esm.js?2b0e:1737 TypeError: _asyncValidator2.default is not a constructor
    at VueComponent.validate (element-ui.common.js?5c96:20130)
    at eval (element-ui.common.js?5c96:19808)
    at Array.forEach (<anonymous>)
    at VueComponent.validate (element-ui.common.js?5c96:19807)
    at VueComponent.submitForm (app.vue?1919:77)
    at click (app.vue?e317:80)
    at VueComponent.invoker (vue.runtime.esm.js?2b0e:2023)
    at VueComponent.Vue.$emit (vue.runtime.esm.js?2b0e:2534)
    at VueComponent.handleClick (element-ui.common.js?5c96:9707)
    at invoker (vue.runtime.esm.js?2b0e:2023)

**Comment by Plortinus** [comment]
更新一下elementui的版本，看看官方文档

**Comment by yuanshengchao** [comment]
版本最新，就是用的官方的demo来的，在别的架构里面正常，放在这个里面就直接报错

**Comment by yuanshengchao** [comment]
还有就是build后没问题，dev有问题，确定是我写法有问题？？？？

**Comment by Plortinus** [comment]
贴代码

**Comment by Plortinus** [comment]
解决办法参考[这里](https://github.com/ElemeFE/element/issues/9476#issuecomment-386938036)

**Comment by yuanshengchao** [comment]
<template>
    <el-form :model="ruleForm2" status-icon :rules="rules2" ref="ruleForm2" label-width="100px" class="demo-ruleForm">
        <el-form-item label="密码" prop="pass">
            <el-input type="password" v-model="ruleForm2.pass" auto-complete="off"></el-input>
        </el-form-item>
        <el-form-item label="确认密码" prop="checkPass">
            <el-input type="password" v-model="ruleForm2.checkPass" auto-complete="off"></el-input>
        </el-form-item>
        <el-form-item label="年龄" prop="age">
            <el-input v-model.number="ruleForm2.age"></el-input>
        </el-form-item>
        <el-form-item>
            <el-button type="primary" @click="submitForm('ruleForm2')">提交</el-button>
            <el-button @click="resetForm('ruleForm2')">重置</el-button>
        </el-form-item>
    </el-form>
</template>
<script>
export default {
    data() {
        var checkAge = (rule, value, callback) => {
            if (!value) {
                return callback(new Error('年龄不能为空'));
            }
            setTimeout(() => {
                if (!Number.isInteger(value)) {
                    callback(new Error('请输入数字值'));
                } else {
                    if (value < 18) {
                        callback(new Error('必须年满18岁'));
                    } else {
                        callback();
                    }
                }
            }, 1000);
        };
        var validatePass = (rule, value, callback) => {
            if (value === '') {
                callback(new Error('请输入密码'));
            } else {
                if (this.ruleForm2.checkPass !== '') {
                    this.$refs.ruleForm2.validateField('checkPass');
                }
                callback();
            }
        };
        var validatePass2 = (rule, value, callback) => {
            if (value === '') {
                callback(new Error('请再次输入密码'));
            } else if (value !== this.ruleForm2.pass) {
                callback(new Error('两次输入密码不一致!'));
            } else {
                callback();
            }
        };
        return {
            ruleForm2: {
                pass: '',
                checkPass: '',
                age: ''
            },
            rules2: {
                pass: [
                    { validator: validatePass, trigger: 'blur' }
                ],
                checkPass: [
                    { validator: validatePass2, trigger: 'blur' }
                ],
                age: [
                    { validator: checkAge, trigger: 'blur' }
                ]
            }
        };
    },
    methods: {
        submitForm(formName) {
            this.$refs[formName].validate((valid) => {
                if (valid) {
                    alert('submit!');
                } else {
                    console.log('error submit!!');
                    return false;
                }
            });
        },
        resetForm(formName) {
            this.$refs[formName].resetFields();
        }
    }
}
</script>

**Comment by yuanshengchao** [comment]
好的，感谢
