### ISSUE TITLE
当有 6 多页面时， build 一直卡着不动，删掉一个多页面能成功 build

### ISSUE THREAD

**Issue by kele59** [Plortinus/vue-multiple-pages#68]
尝试了多次， 一旦超过 5 个多页面，build 就会一直卡着不动

**Comment by kele59** [comment]
同时mac 电脑风扇一直在转。。。

**Comment by kele59** [comment]
https://github.com/vuejs/vue-cli/issues/2318
看来是 vue-cli 的问题

**Comment by RYUDEN** [comment]
项目写到一部分的时候，。。。
出现这个问题也是气人
