### ISSUE TITLE
Extra code?

### ISSUE THREAD

**Issue by Gargo** [Plortinus/vue-multiple-pages#70]
For example the project contains multiple instances of home (+number at the end). In the same time the readme is semiempty. So did you create these multiple instances of the same file on purpose?

**Comment by Plortinus** [comment]
Multiple pages can be see as multiple single page application.Each application should has a entry js file called `app.js`.

**Comment by Gargo** [comment]
@Plortinus but in this case you defined the same page multiple times. So maybe I don't understand - could you explain in other words?

**Comment by Plortinus** [comment]
In SPA,the webpack has only one entry js file.So in multiple pages application,there should be multiple entries，each entry js file importing a vue file.
My example is just an example for explainning how to create new pages.
