### ISSUE TITLE
npm run buid后文件路径不对

### ISSUE THREAD

**Issue by TOBOM** [Plortinus/vue-multiple-pages#8]
应该在输出的html里的引用中加上../,求大神更新,改了好久都不对

**Comment by TOBOM** [comment]
以修复
` resolve: {
    extensions: ['.js', '.vue'],
    alias: {
      assets: join(__dirname, './src/assets'),
      components: join(__dirname, './src/components'),
      root: join(__dirname, 'node_modules')
    }
  },`这段代码里加./相对路劲就行了

**Comment by TOBOM** [comment]
output: {
    path: resolve(__dirname, './dist'),
    filename: '[name].js',
    publicPath: '/'


这里面的publicPath: '/'这样能npm run dev正常访问,但是npm run build出来的文件引用地址不对
改成publicPath: '../',打包出来的dist文件路劲都对了,但是npm run dev不能正常访问

**Comment by Plortinus** [comment]
`npm run build`之后不能直接访问,需要再起个终端运行`node server.js`这样就能看到实际效果,生产环境也是这个原理

**Comment by TOBOM** [comment]
我打包以后使用nginx运行的,publicPath: '/'能访问,打包以后的路劲是src="/assets/js/vendors.js?196199a6dc35738c6c61">,其实应该是src="../assets/js/vendors.js?196199a6dc35738c6c61">才能访问,
怎么把2个地址分开,一个用publicPath: '/',一个用publicPath: '../'

**Comment by TOBOM** [comment]
求大神给个方案,不然每次运行改一次,打包改一次有点麻烦

**Comment by Plortinus** [comment]
nginx 监听打包后的dist目录就可以了,不行就再监听上一层,试试这样

**Comment by nikoohp** [comment]
可以根据环境变量来分别设置`publicPath`
