### ISSUE TITLE
CSS output issue

### ISSUE THREAD

**Issue by lavezzi1** [Plortinus/vue-multiple-pages#9]
I created modal.vue components which looks like this:

```
<template>
...
</template>

<script>
...
</script>

<style lang="css">
.modal {...}
</style>
```

Works good, but when I run **npm run build** css doesn't have css code for modal. What's wrong?
Looks like it doesn't extract css from .vue files.

**Comment by Plortinus** [comment]
The css code for modal is created in the '<style></style>' markup of the html.The extracted css is the common part among all the entries.

**Comment by lavezzi1** [comment]
@Plortinus but output .css file doesn't contains css code for modal. Another problem that I found is: I have two pages, if they are both have imported modal `import Modal from 'components/modal.vue'` everything works fine, but if one haven't the output .css file doesn't have css code for modal. How can I fix that?

**Comment by Plortinus** [comment]
I changed the `webpack.config.js`. Now, it can extract css from the `.vue` file into a single css file for that page.

**Comment by lavezzi1** [comment]
@Plortinus thank you man, you're amazing. Can please show how to setup up postcss? I tried this but seems like it doesn't works
```
{
                test: /\.vue$/,
                loader: 'vue-loader',
                options: {
                    loaders: {
                        css: ExtractTextPlugin.extract({
                            fallback: 'style-loader'
                            use: [
                                {
                                    loader: 'css-loader',
                                    options: { importLoaders: 1 }
                                },
                                'postcss-loader'
                            ]
                        })
                    }
                }
            },
```

**Comment by Plortinus** [comment]
Check `postcss` branch to see the changes.

**Comment by lavezzi1** [comment]
@Plortinus Great, thank you so much. To be able to compile postcss from .css files I need to add this: 
```
{
                test: /\.css$/,
                use: ExtractTextPlugin.extract({
                    use: ['css-loader', 'postcss-loader'],
                    fallback: 'style-loader'
                })
            },
```

Right?

**Comment by Plortinus** [comment]
Yes that's right
